---
name: on_hello_event1
pack: hello_st2
description: Sample rule firing on hello_st2.event1.
enabled: false
trigger:
    type: hello_st2.event1
action:
    ref: hello_st2.greet
    parameters:
        greeting: Yo
